sudo: required
dist: trusty

language: python
python:
- '3.5'

env:
- TOXENV=py27
- TOXENV=py35
- TOXENV=qa

install:
- test "$TOXENV" = "qa" || travis_retry sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
- test "$TOXENV" = "qa" || travis_retry sudo apt-get update -y
- test "$TOXENV" = "qa" || travis_retry sudo apt-get install -y lxd
- test "$TOXENV" = "qa" || sudo lxd init --auto
- test "$TOXENV" = "qa" || sudo lxc list
- travis_retry pip install -U pip
- travis_retry pip install tox codecov

script:
- sudo DEBUG=1 $(which tox) -e $TOXENV

after_success:
- codecov

cache:
  directories:
  - "$HOME/.cache/pip"

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
